### ISSUE TITLE
How do you pass in a Referrer Header?

### ISSUE THREAD

**Issue by SachinKainth** [urielha/log4stash-old#8]
How do you pass in a Referrer Header to ElasticSearch using Log4Stash?

**Comment by urielha** [comment]
Anyway you like :)
In what format are you logging?

Lets say you do something like this:

``` C#
logger.infoFormat(".. Referrer={0} ...", referrer);
```

you can use the `kv` filter to extract the referrer automatically, just add `<kv />` to you configuration xml
example:

``` XML
<appender name="ElasticSearchAppender" type="log4net.ElasticSearch.ElasticSearchAppender, log4stash">
    <Server>localhost</Server>
    <Port>9200</Port>
    <ElasticFilters>

      <!-- using keyValue filter to extract key=value format from the log message -->
      <kv /> 

    </ElasticFilters>
</appender>
```

Another way is to use the `Grok` filter
In our case,  instead of `<kv />` we will use:

``` XML
<Grok>
     <SourceKey>Message</SourceKey>
     <Pattern>Referrer=%{URI:Referrer}</Pattern>
</Grok>
```

I didn't write full documentation about the filters 
_(I will very appreciate some help with the documentation :sweat_smile: )_ 

But they pretty similar to  [logstash filters](https://www.elastic.co/guide/en/logstash/current/filter-plugins.html)
you can read about logstash's [kv filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html) and [Grok filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html) respectively
